import React,{useState} from 'react';
import {signIn,signOut} from './accountClient';
import './account.css';
export function AccountPanel({account,sync,onRetry,onImport}){
 const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[importing,setImporting]=useState(false),[reloading,setReloading]=useState(false);
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const result=await signIn(mode,{email:email.trim(),password,name:name.trim()});setPassword('');if(result.verificationRequired){setMessage('请查收验证邮件，完成邮箱验证后回来登录。');setMode('login')}else location.reload()}catch(e){setError(e.message||'暂时无法连接，请稍后重试。')}finally{setBusy(false)}};
 if(account)return <div className="account-panel"><div className="account-person"><span>{(account.user.name||account.user.email)[0]}</span><div><h3>{account.user.name||'小芽同学'}</h3><p>{account.user.email}</p></div></div><p className="account-sync" role="status">{sync}</p><button className="outline-button full" onClick={()=>setReloading(true)}>重新加载云端记录</button>{reloading&&<div className="account-import"><p>重新加载会用云端版本替换当前账号的本机记录。请先保留尚未同步的新改动。</p><button className="btn purple full" onClick={()=>{setReloading(false);onRetry()}}>确认加载云端版本</button><button className="text-link" onClick={()=>setReloading(false)}>取消</button></div>}<div className="account-import"><h4>带上之前的好物</h4><p>可将这台设备的访客收藏和发布记录合并到当前账号，同编号物品保留账号中的版本。</p>{importing?<><button className="btn purple full" onClick={()=>{onImport();setImporting(false);setMessage('访客记录已合并，同步状态见上方。')}}>确认合并到这个账号</button><button className="text-link" onClick={()=>setImporting(false)}>取消</button></>:<button className="text-link" onClick={()=>setImporting(true)}>导入访客记录</button>}</div>{message&&<p role="status">{message}</p>}<button className="text-link" onClick={signOut}>退出登录</button></div>;
 return <div className="account-panel"><p className="account-lead">让收藏、发布记录和小芽成长跟着你走。</p><div className="account-tabs" role="group" aria-label="账号操作"><button aria-pressed={mode==='login'} onClick={()=>{setMode('login');setError('')}}>登录</button><button aria-pressed={mode==='signup'} onClick={()=>{setMode('signup');setError('')}}>注册</button></div><form onSubmit={submit}>{mode==='signup'&&<label className="field">昵称<input value={name} onChange={e=>setName(e.target.value)} maxLength={30} placeholder="怎么称呼你" autoComplete="nickname" required/></label>}<label className="field">邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} autoComplete="email" placeholder="你的常用邮箱" required/></label><label className="field">密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} maxLength={128} autoComplete={mode==='signup'?'new-password':'current-password'} placeholder="至少 8 位" required/></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<button className="btn purple full" disabled={busy}>{busy?'请稍等…':mode==='login'?'登录小芽接力':'创建账号'}</button></form><p className="account-footnote">未登录时也可以逛市集。访客记录保留在这台设备，登录后可选择导入。</p></div>;
}
