import React from 'react';
import {ArrowLeft,Recycle,MapPin,CaretDown,MagnifyingGlass,IdentificationCard,X,Camera,BookOpen,Armchair,Plant,SquaresFour,ArrowUpRight,Plus,Heart,UserCircle,ChatCircleDots,Sparkle,Package,ArrowRight} from '@phosphor-icons/react';

const categories=[['全部好物','全部',SquaresFour],['数码装备','数码',Camera],['书籍文具','书籍画材',BookOpen],['宿舍好物','宿舍',Armchair],['绿植生活','绿植',Plant]];
export function MobileHeader({view,free,scope,onCampus,onLookup,onBack}){
 return <header className="app-mobile-header">{view==='saved'&&(<button className="mobile-back" aria-label="返回上一页" onClick={onBack}><ArrowLeft size={22}/></button>)}<div className="mobile-wordmark"><b>{view==='mine'?'我的接力':view==='messages'?'消息':view==='saved'?'我的收藏':free?'免费接力':'接力卡'}</b></div><button className="mobile-school" onClick={onCampus}><MapPin size={14}/><span>{scope==='all'?'小谷围 · 全岛':scope}</span><CaretDown size={12}/></button><button className="mobile-tool" aria-label="查询物品身份" onClick={onLookup}><IdentificationCard size={23}/></button></header>
}
export function MobileDiscover({free,view,query,setQuery,cat,setCat,sort,setSort,onBrowse,onPublish,onAssistant}){
 return <section className="mobile-discover" aria-label="手机发现页">
  <div className="mobile-search"><MagnifyingGlass size={21}/><input aria-label="手机搜索好物" placeholder={free?'找一件需要的免费好物':'搜好物、物品编号、同学'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空手机搜索" onClick={()=>setQuery('')}><X size={18}/></button>}</div>
  {view!=='saved'&&!free&&<><div className="mobile-category-grid" aria-label="物品分类">{categories.map(([value,label,Icon])=><button key={value} aria-pressed={cat===value} onClick={()=>setCat(value)}><span><Icon size={27} weight={cat===value?'fill':'duotone'}/></span>{label}</button>)}</div><div className="mobile-feature-grid"><button className="mobile-free-feature" onClick={()=>onBrowse('免费接力')}><span className="feature-kicker">FREE RELAY</span><b>好物免费接力<ArrowUpRight size={19}/></b><small>把闲置，送给刚好需要的人</small><Recycle size={42} weight="duotone"/></button><button className="mobile-ai-feature" onClick={onAssistant}><Sparkle size={27} weight="duotone"/><b>有问题？问 AI</b><small>发布、来源、交接</small></button></div></>}
  {free&&<div className="mobile-free-panel"><div><span className="feature-kicker">不用标价，也值得被珍惜</span><h2>送一件好物，<br/>接一段故事。</h2><p>按需领取 · 先确认状况 · 校门交接</p><button onClick={()=>onPublish('free')}>我有好物想送<Plus size={17}/></button></div><Recycle size={66} weight="duotone"/></div>}
  <div className="mobile-feed-heading"><h2>{view==='saved'?'留给心动的好物':free?'等待下一位主人':cat==='全部好物'?'发现好物':categories.find(c=>c[0]===cat)?.[1]+'好物'}</h2><label><select aria-label="手机商品排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">最新发布</option><option value="low">价格最低</option><option value="high">价格最高</option></select><CaretDown size={13}/></label></div>
 </section>
}
export function MobileProfile({school,saved,drafts,onSaved,onCampus,onAbout,onGarden,growthPoints}){
 return <section className="mobile-profile"><div className="mobile-profile-person"><UserCircle size={56} weight="duotone"/><div><h1>我的校园接力</h1><button onClick={onCampus}>{school}<CaretDown size={12}/></button><small>本机演示身份 · 尚未接入账号</small></div></div><div className="mobile-profile-stats"><button onClick={onSaved}><Heart size={23}/><b>{saved}</b><span>我的收藏</span></button><a href="#my-listings"><Package size={23}/><b>{drafts.length}</b><span>我发布的</span></a><a href="#my-listings"><Recycle size={23}/><b>{drafts.filter(d=>Number(d.price)===0).length}</b><span>免费发布</span></a></div><button className="garden-entry" onClick={onGarden}><Plant size={30} weight="duotone"/><span><b>我的接力树</b><small>{growthPoints} 成长值 · 让好物长出新故事</small></span><ArrowRight size={19}/></button><button className="profile-about" onClick={onAbout}>物品身份与记录来源 <ArrowRight size={18}/></button></section>
}
export function MobileMessages({onAssistant,onBrowse}){
 return <section className="mobile-messages"><h1>消息</h1><p className="messages-caption">沟通和平台帮助，在这里找到。</p><button className="assistant-inbox" onClick={onAssistant}><span><Sparkle size={29} weight="duotone"/></span><div><b>接力卡使用助手</b><small>不知道怎么发布？点这里问一问</small></div><ArrowRight size={19}/></button><div className="messages-empty"><ChatCircleDots size={54} weight="duotone"/><h2>还没有真实会话</h2><p>目前仅提供物品问答演示。<br/>真实私信、预约和消息提醒尚未接入。</p><button className="btn purple" onClick={()=>onBrowse()}>去发现好物 <ArrowRight size={18}/></button></div></section>
}
