import React,{useState,useRef,useEffect} from 'react';
import {Receipt,UploadSimple,Sparkle,CheckCircle,X} from '@phosphor-icons/react';
import {readPhoto} from './Publish';
import {analyzeOrderScreenshot,aiAvailable} from './ai';
import './order-screenshot.css';

export function OrderScreenshot({onApply,disabled=false}){
 const [image,setImage]=useState(''),[result,setResult]=useState(null),[selected,setSelected]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[applied,setApplied]=useState('');
 const request=useRef(),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;request.current?.abort();request.current=null},[]);
 const clear=()=>{generation.current++;request.current?.abort();request.current=null;setBusy(false);setImage('');setResult(null);setError('');setApplied('')};
 const upload=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const token=++generation.current;request.current?.abort();request.current=null;setResult(null);setApplied('');setBusy(true);setError('');setImage('');try{const src=await readPhoto(file);if(generation.current===token)setImage(src)}catch(e){if(generation.current===token)setError(e.message)}finally{if(generation.current===token)setBusy(false)}};
 const recognize=async()=>{if(!image||busy)return;const token=generation.current;const controller=new AbortController();request.current=controller;setBusy(true);setError('');setApplied('');setResult(null);const timer=setTimeout(()=>controller.abort(),60000);try{const data=await analyzeOrderScreenshot(image,controller.signal);if(token===generation.current){setResult(data);setSelected(0)}}catch(e){if(token===generation.current)setError(e.name==='AbortError'?'识别超时，截图已保留，可以重试或手动填写。':e.message)}finally{clearTimeout(timer);if(request.current===controller){request.current=null;setBusy(false)}}};
 const item=result?.items[selected];
 const apply=scope=>{if(!item)return;onApply({...item,purchaseDate:result.purchaseDate,platform:result.platform},image,scope);setApplied(scope==='history'?'历史信息已带入，请核对原截图与金额。':'商品信息已带入；请补充真实照片和当前状况。')};
 return <details className="order-import"><summary><Receipt size={21}/>订单截图自动填写（可选）</summary><div className="order-import-body"><p>从购买记录带入名称、规格、实付金额和时间，少填几次表。</p><label className={`order-upload ${image?'has-image':''}`}><input type="file" accept="image/*" aria-label="上传订单截图" disabled={disabled||busy} onChange={upload}/>{image?<img src={image} alt="待识别的订单截图，仅在这里预览"/>:<UploadSimple size={30}/>}<span>{image?'更换订单截图':'上传一张清楚的订单截图'}</span></label><small>建议先遮住姓名、电话、地址和订单号。截图不会用作商品主图。</small><div className="order-actions"><button type="button" className="btn purple" disabled={disabled||busy||!image||!aiAvailable} onClick={recognize}><Sparkle size={17}/>{busy?'正在识别…':'识别这张截图'}</button>{image&&<button type="button" className="text-link" disabled={disabled} onClick={clear}><X size={16}/>清除预览</button>}</div><small>{aiAvailable?'点击识别会将这张截图发送到图片识别服务；核对后再带入表单。':'图片识别服务尚未连接。你可以保留截图并手动填写，图片不会上传。'}</small>{error&&<p role="alert" className="error">{error}</p>}{result&&item&&<section className="order-result" aria-label="订单识别候选信息"><h3>识别结果 · 待核对</h3>{result.items.length>1&&<label className="field">选择要接力的商品<select value={selected} onChange={e=>{setSelected(Number(e.target.value));setApplied('')}}>{result.items.map((i,n)=><option key={n} value={n}>{i.name}</option>)}</select></label>}<dl><div><dt>商品名称</dt><dd>{item.name}</dd></div><div><dt>规格</dt><dd>{item.specification||'未识别，请补充'}</dd></div><div><dt>单件实付</dt><dd>{item.purchasePrice==null?'无法确认，请手动核对':`¥${item.purchasePrice}`}</dd></div><div><dt>购买时间</dt><dd>{result.purchaseDate||'未识别'}</dd></div><div><dt>订单来源</dt><dd>{result.platform}</dd></div></dl><p className="order-status">{result.orderStatus==='completed'?'截图显示已完成，仍需确认属于这件物品。':'截图未明确证明完成交易，填入历史信息前请核对订单状态。'}</p><div className="order-actions"><button type="button" className="outline-button" disabled={disabled} onClick={()=>apply('listing')}>带入商品信息</button><button type="button" className="outline-button" disabled={disabled} onClick={()=>apply('history')}>带入历史记录</button></div><small>只在点击后替换对应字段；当前售价、成色和功能由你确认。表单仍可修改。</small></section>}{applied&&<p className="order-applied" role="status"><CheckCircle size={18}/>{applied}</p>}</div></details>;
}
