import React,{useState,useRef,useEffect} from 'react';
import {Camera,Check,CheckCircle,ArrowLeft,ArrowRight,Sparkle,MapPin,UploadSimple} from '@phosphor-icons/react';
import {schools,gates,meetingLabel,validMeeting} from './island';
import {analyzePhoto,aiAvailable} from './ai';
const categories=['数码装备','书籍文具','宿舍好物','绿植生活'];
function readPhoto(file){return new Promise((resolve,reject)=>{if(!file?.type.startsWith('image/')||file.size>8*1024*1024)return reject(new Error('请选择小于 8 MB 的 JPG、PNG 或其他支持的图片。'));const r=new FileReader();r.onerror=()=>reject(new Error('图片读取失败'));r.onload=()=>{const p=new Image();p.onload=()=>{const s=Math.min(1,1200/Math.max(p.width,p.height)),c=document.createElement('canvas');c.width=Math.round(p.width*s);c.height=Math.round(p.height*s);c.getContext('2d').drawImage(p,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.88))};p.onerror=()=>reject(new Error('无法打开这张图片，请换一张 JPG 或 PNG。'));p.src=r.result};r.readAsDataURL(file)})}
function brighten(src){return new Promise((resolve,reject)=>{const p=new Image();p.onload=()=>{const c=document.createElement('canvas');c.width=p.width;c.height=p.height;const ctx=c.getContext('2d');ctx.filter='brightness(1.06)';ctx.drawImage(p,0,0);resolve(c.toDataURL('image/jpeg',.9))};p.onerror=()=>reject(new Error('调整失败，请保留原图'));p.src=src})}
export function Publish({Modal,close,submit,school}){
 const [step,setStep]=useState(1),[d,setD]=useState({name:'',image:'',originalImage:'',description:'',category:'宿舍好物',condition:'见物品描述',price:'',school:school||schools[0],gate:'',history:'unknown',proof:'',previousPrice:'',date:'',source:'',sellerFaq:'',confirmed:false}),[extra,setExtra]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[adjusted,setAdjusted]=useState(false),[showOriginal,setShowOriginal]=useState(false),[guidance,setGuidance]=useState(''),[consent,setConsent]=useState(false);
 const controller=useRef();useEffect(()=>()=>controller.current?.abort(),[]);
 const set=(k,v)=>setD(p=>({...p,[k]:v,confirmed:k==='confirmed'?v:false}));
 const upload=async(e,k)=>{const file=e.target.files?.[0];if(!file)return;controller.current?.abort();setBusy(true);try{const src=await readPhoto(file);if(k==='image'){setD(v=>({...v,image:src,originalImage:src,confirmed:false}));setAdjusted(false);setGuidance('')}else if(k==='proof')set('proof',src);else setExtra(v=>({...v,[k]:src}));setError('')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const analyze=async()=>{if(!d.image||!consent||busy)return;setBusy(true);setError('');controller.current=new AbortController();const timer=setTimeout(()=>controller.current?.abort(),20000);try{const r=await analyzePhoto(d.originalImage,controller.current.signal);setD(v=>({...v,name:r.name,description:r.description,confirmed:false}));setGuidance(r.guidance||'候选描述已整理。请核对功能、缺陷和配件，AI 无法确认转手历史。');setStep(2)}catch(e){setError(e.name==='AbortError'?'AI 请求已取消或超时，可以继续手动填写。':e.message)}finally{clearTimeout(timer);setBusy(false)}};
 const adjust=async()=>{setBusy(true);try{if(adjusted){set('image',d.originalImage);setAdjusted(false)}else{set('image',await brighten(d.originalImage));setAdjusted(true)}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const next=()=>{if(step===1&&!d.image)return setError('先拍摄或上传一张物品正面照片。');if(step===2){if(!d.name.trim()||!d.description.trim()||d.price===''||!Number.isFinite(Number(d.price))||Number(d.price)<0)return setError('请确认名称、真实状况和有效报价，免费填 0。');if(d.history==='upload'&&(!d.proof||d.previousPrice===''||!Number.isFinite(Number(d.previousPrice))||Number(d.previousPrice)<0||!d.source.trim()))return setError('请补全凭证、可确认的历史价格及凭证来源。')}setError('');setStep(v=>v+1)};
 const finish=()=>{if(!validMeeting(d.school,d.gate)||!d.confirmed)return setError('请选择规定交接点，并确认信息。');submit({...d,photos:extra,imageAdjusted:adjusted,pickup:meetingLabel(d.school,d.gate),id:`ITEM-${Date.now().toString(36).toUpperCase()}`,price:Number(d.price),owner:'我',platform:[],uploaded:d.history==='upload'?[{price:Number(d.previousPrice),date:d.date||'时间未知',source:d.source,proof:d.proof}]:[],status:'REVIEW',version:1,time:0})};
 return <Modal title="三步，让好物接力" close={close}><div className="steps">{['拍张照','确认信息','选择交接点'].map((s,i)=><span key={s} className={step===i+1?'active':step>i+1?'done':''} aria-current={step===i+1?'step':undefined}><b>{step>i+1?<Check size={14}/>:i+1}</b>{s}</span>)}</div>
 {step===1&&<><p className="modal-lead">先拍清楚，其他信息慢慢补。</p><label className={`upload-zone ${d.image?'has-photo':''}`}><input disabled={busy} type="file" accept="image/*" aria-label="上传物品照片" onChange={e=>upload(e,'image')}/>{d.image?<img src={showOriginal?d.originalImage:d.image} alt={showOriginal?'物品原图':'物品发布照片'}/>:<><Camera size={38}/><b>拍照或从相册选择</b><span>正面全貌 · 保留边缘 · 使用自然光</span></>}</label>{d.image&&<div className="photo-controls"><button className="outline-button" disabled={busy} onClick={adjust}>{adjusted?'恢复原图':'轻微提亮'}</button><label><input type="checkbox" checked={showOriginal} onChange={e=>setShowOriginal(e.target.checked)}/>对照原图</label><small>不修补划痕、不改颜色、不替换背景</small></div>}<div className="shoot-guide"><b>换个角度，更少来回问</b><p>① 正面拍完整　② 侧面拍接口或尺寸　③ 靠近拍划痕和缺陷</p></div><div className="extra-photos">{[['side','补一张侧面'],['defect','补一张缺陷特写']].map(([k,label])=><label key={k}><input disabled={busy} type="file" accept="image/*" aria-label={label} onChange={e=>upload(e,k)}/>{extra[k]?<img src={extra[k]} alt={label}/>:<Camera size={23}/>}<span>{label}（可选）</span></label>)}</div><div className="ai-photo"><b><Sparkle size={20}/>AI 帮你整理照片信息</b><p>{aiAvailable?'识别名称、整理可见状况，并建议补拍角度。结果需要你确认。':'AI 图片识别尚未连接，当前提供拍摄指导和本地提亮。可以继续手动填写。'}</p>{aiAvailable&&<label className="checkbox-line"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意将本张物品照片发送到配置的 AI 服务</label>}<button className="btn purple" disabled={!aiAvailable||!consent||!d.image||busy} onClick={analyze}>{busy?'正在处理…':'AI 生成信息草稿'}</button></div></>}
 {step===2&&<>{guidance&&<div className="notice compact">{guidance}</div>}<div className="mini-publish-photo"><img src={d.image} alt="物品照片"/><p>只需确认名称、报价和真实状况。<br/>记不清的信息，可以保留未知。</p></div><label className="field">物品名称<input maxLength={40} value={d.name} onChange={e=>set('name',e.target.value)} placeholder="例如：可调节暖光台灯"/></label><div className="form-row"><label className="field">分类<select value={d.category} onChange={e=>set('category',e.target.value)}>{categories.map(s=><option key={s}>{s}</option>)}</select></label><label className="field">你的报价（免费填 0）<input type="number" min="0" value={d.price} onChange={e=>set('price',e.target.value)}/></label></div><label className="field">真实状况、缺陷与配件<textarea rows={3} value={d.description} onChange={e=>set('description',e.target.value)} placeholder="请说明能否正常使用、哪里有磨损、包含哪些配件。"/></label><label className="field">物品助手可回复的补充信息（可选）<textarea rows={2} value={d.sellerFaq} onChange={e=>set('sellerFaq',e.target.value)} placeholder="例如：灯杆高 40 厘米，包含电源线。请只填写你确认的信息。"/></label><details className="history-disclosure"><summary>补充历史来源（可选，默认未知）</summary><label className="field">此前交易记录<select value={d.history} onChange={e=>set('history',e.target.value)}><option value="unknown">不知道／没有记录</option><option value="statement">有过交易，仅物主陈述</option><option value="upload">有凭证，可上传</option></select></label>{d.history==='upload'&&<><label className="upload-zone small-upload"><input type="file" accept="image/*" aria-label="上传历史交易凭证" onChange={e=>upload(e,'proof')}/><UploadSimple size={24}/>{d.proof?'凭证已添加，点击更换':'添加历史凭证'}</label><label className="field">凭证可确认的历史价格<input type="number" min="0" value={d.previousPrice} onChange={e=>set('previousPrice',e.target.value)}/></label><label className="field">凭证来源<input value={d.source} onChange={e=>set('source',e.target.value)} placeholder="例如：闲鱼订单截图"/></label><label className="field">时间（可选）<input type="month" value={d.date} onChange={e=>set('date',e.target.value)}/></label></>}<p className="fine-print">上传记录与平台记录分开保存，无记录不等于首次转手。</p></details></>}
 {step===3&&<><div className="publish-preview"><img src={d.image} alt={d.name}/><div><span className="eyebrow">待确认的接力卡</span><h3>{d.name}</h3><strong>{Number(d.price)===0?'免费':`¥${d.price}`}</strong><p>{d.description}</p></div></div><label className="field">交接学校<select value={d.school} onChange={e=>{set('school',e.target.value);set('gate','')}}>{schools.map(s=><option key={s}>{s}</option>)}</select></label><div className="meeting-options" role="group" aria-label="选择规定交接点">{gates.map(g=><button aria-pressed={d.gate===g.id} className={d.gate===g.id?'selected':''} key={g.id} onClick={()=>set('gate',g.id)}><MapPin size={24}/><b>{g.name}</b><small>校门外公共区域</small>{d.gate===g.id&&<CheckCircle size={21}/>}</button>)}</div><p className="fine-print">交接范围限小谷围岛。教学区和生活区门口为可选类型，具体门名与见面位置请双方在聊天中确认。跨校不安排进入校内。</p><div className="notice compact">历史来源：{d.history==='upload'?'上传凭证':d.history==='statement'?'物主陈述':'未知'}。发布后物品助手只引用本版确认的信息。</div><label className="checkbox-line"><input type="checkbox" checked={d.confirmed} onChange={e=>set('confirmed',e.target.checked)}/>我已确认照片保留真实缺陷、报价、物品描述和交接范围。</label><p className="fine-print">提交后仍需工作人员审核。当前为本地演示，不会创建真实订单。</p></>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions">{step>1&&<button className="outline-button" disabled={busy} onClick={()=>{setStep(v=>v-1);set('confirmed',false);setError('')}}><ArrowLeft size={17}/>上一步</button>}{step<3?<button className="btn purple" disabled={busy} onClick={next}>{step===1?'确认照片，继续':'选择交接点'}<ArrowRight size={17}/></button>:<button className="btn purple" disabled={!d.confirmed||!validMeeting(d.school,d.gate)||busy} onClick={finish}>确认并提交审核<CheckCircle size={18}/></button>}</div></Modal>
}
