import React,{useState,useEffect,useRef} from 'react';
import {Tree,Leaf,Star,Ticket,ArrowRight,CheckCircle,Lock,Recycle,Sparkle} from '@phosphor-icons/react';
import {emptyGarden,awardRelay,growth,redeemBoost} from './relayGame';
import './relay-garden.css';
const asset=name=>`${import.meta.env.BASE_URL}assets/${name}`;
const photo=e=>e.image||asset(e.img==='plant'?'plant-new.png':`${e.img||'chair'}.jpg`);
export function RelayGarden({garden,setGarden,drafts,items,initialTab='stories',compact=false}){
 const [practice,setPractice]=useState(false),[sample,setSample]=useState(emptyGarden),[tab,setTab]=useState(initialTab),[selected,setSelected]=useState(null),[story,setStory]=useState(''),[offer,setOffer]=useState(''),[notice,setNotice]=useState(''),[sender,setSender]=useState(false),[receiver,setReceiver]=useState(false);
 const editorRef=useRef(),sceneRef=useRef();
 useEffect(()=>{if(selected)editorRef.current?.scrollIntoView({behavior:'smooth',block:'center'})},[selected]);
 const current=practice?sample:garden,stats=growth(current),eligible=drafts.filter(i=>i.status==='PUBLISHED'&&i.confirmed&&!i.sold&&Number(i.price)>0),available=current.coupons.filter(c=>!c.usedAt);
 const write=practice?setSample:setGarden;
 const switchMode=value=>{setPractice(value);setSelected(null);setNotice('');setTab('stories')};
 const experience=()=>{if(!sender||!receiver)return;const source=items.find(i=>i.price===0)||items[0];if(!source)return;setSample(g=>awardRelay(g,{...source,id:'PRACTICE-GIFT',price:0,status:'PUBLISHED',sold:false,confirmed:true}));setNotice('示例接力完成：+40 成长值，+2 张示例券。未改变你的物品或真实记录。');setTimeout(()=>sceneRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),30)};
 const adopt=()=>{if(practice){setNotice('示例券只用于了解规则，不会改变市集排序。');return;}const result=redeemBoost(garden,available[0]?.id,eligible.find(i=>i.id===offer));if(result.error)setNotice(result.error);else{setGarden(result.garden);setNotice('已进入本机推荐演示，24 小时后自动结束。成长值保持不变。')}};
 const saveStory=()=>{write(g=>({...g,events:g.events.map(e=>e.id===selected.id?{...e,story:story.trim()}:e)}));setSelected(null);setNotice('故事已保存在当前记录中。')};
 return <div className={`relay-garden ${compact?"is-compact":""}`}><div className="garden-intro"><span>PASS IT ON, WATCH IT GROW</span><h3>让每一次接力，都长出新故事。</h3><p>好物继续被使用，你的树也慢慢长大。</p></div><div className="garden-modes" role="group" aria-label="接力树模式"><button aria-pressed={!practice} onClick={()=>switchMode(false)}>我的接力树</button><button aria-pressed={practice} onClick={()=>switchMode(true)}>示例体验</button></div><p className="garden-demo"><Sparkle size={15}/>{practice?'独立示例：不增加个人奖励，不改变交易记录。':'本机养成演示 · 奖励不代表真实公益或跨用户推流。'}</p>
 <section ref={sceneRef} className="garden-scene" aria-label="接力树照片墙"><img className="garden-art" src={asset('relay-tree.webp')} alt="草地上伸展的紫色手绘树枝"/><div className="garden-scene-title"><span>MY RELAY TREE</span><b>{stats.level.name}</b></div>{Array.from({length:6},(_,n)=>{const event=current.events[n];return event?<button key={n} className={`tree-memory branch-${n}`} onClick={()=>{setSelected(event);setStory(event.story)}} aria-label={`查看接力故事：${event.name}`}><img src={photo(event)} alt={event.name}/><span>{event.free?'免费接力':'好物接力'}<Star size={10} weight="fill"/></span></button>:<div key={n} className={`tree-bud branch-${n}`}><Leaf size={20} weight="duotone"/><span>{n===0?'等第一段故事':'待生长'}</span></div>})}<div className="garden-scene-footer"><Leaf size={17}/>{current.events.length?`${current.events.length} 段故事，在这里继续生长`:'每件好物，都可以是新故事的开始'}</div></section>
 <div className="garden-stats"><div><b>{stats.points}</b><span>成长值</span></div><div><b>{stats.freeCount}</b><span>免费接力</span></div><div><b>{available.length}</b><span>{practice?'示例曝光券':'可用演示券'}</span></div></div><div className="garden-progress"><div><b>{stats.level.name}</b><span>{stats.next?`再 ${stats.next.at-stats.points} 点 · ${stats.next.name}`:'所有成长阶段已解锁'}</span></div><progress max={stats.next?.at||120} value={Math.min(stats.points,stats.next?.at||120)}/><p>种子 → 新叶 → 故事枝头 → 接力小岛</p></div>
 {practice&&<section className="garden-practice"><h4><Recycle size={20}/>体验一次免费接力</h4><p>模拟把闲置花盆送给需要的同学，观察树和奖励的变化。</p><label><input type="checkbox" checked={sender} onChange={e=>setSender(e.target.checked)}/>模拟物主确认已交接</label><label><input type="checkbox" checked={receiver} onChange={e=>setReceiver(e.target.checked)}/>模拟接收者确认已收到</label><button className="btn purple full" disabled={!sender||!receiver||sample.events.length>0} onClick={experience}>{sample.events.length?'示例接力已完成':'完成示例接力，看看树的变化'}</button></section>}
 {notice&&<p className="garden-notice" role="status"><CheckCircle size={18}/>{notice}</p>}
 <div className="garden-tabs" role="group" aria-label="查看接力树内容">{[['stories','接力故事'],['coupons','曝光券'],['rules','成长规则']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='stories'&&<section className="garden-stories">{!current.events.length?<div className="garden-empty"><Tree size={32}/><h4>这里会留下你的接力故事</h4><p>在“我的”完成一件已发布物品的双方确认演示，即可获得成长。历史截图不会兑换奖励。</p>{!practice&&<button className="text-link" onClick={()=>switchMode(true)}>先体验树怎么长大 <ArrowRight size={17}/></button>}</div>:current.events.slice().reverse().map(e=><button className="garden-story" key={e.id} onClick={()=>{setSelected(e);setStory(e.story)}}><img src={photo(e)} alt=""/><div><b>{e.name}</b><small>{e.free?'免费接力':'普通交易'} · +{e.points} 成长值</small><p>{e.story||'写下一句，这件物品的新故事。'}</p></div><ArrowRight size={17}/></button>)}</section>}
 {tab==='coupons'&&<section className="garden-coupons"><h4><Ticket size={22}/>{available.length} 张{practice?'示例券':'演示曝光券'}</h4><p>选择自己已发布的收费好物，进入当前浏览器的“接力推荐”位置 24 小时。不影响搜索和价格排序，不保证浏览或成交。</p>{available.length>0?<><label className="field">选择在售物品<select value={offer} onChange={e=>setOffer(e.target.value)} disabled={practice}><option value="">{practice?'示例体验不能推广真实物品':'选择我的已发布物品'}</option>{eligible.map(i=><option key={i.id} value={i.id}>{i.name} · ¥{i.price}</option>)}</select></label>{!practice&&!eligible.length&&<small>暂无可用物品：需要自己已发布、仍在售且价格大于 0。</small>}<button className="btn purple full" onClick={adopt} disabled={!practice&&!offer}>使用 1 张{practice?'示例券':'演示券'}</button></>:<div className="garden-empty"><Lock size={25}/><p>完成一次接力后获得。每件物品只奖励一次。</p></div>}<small>每 7 天可使用 1 次 · 用券不扣成长值 · 未使用的券保留</small>{!practice&&garden.boosts.length>0&&<div className="garden-redemptions"><h4>使用记录</h4>{garden.boosts.slice().reverse().map(b=><p key={b.startedAt}>{drafts.find(d=>d.id===b.itemId)?.name||b.itemId}<br/><small>{b.expiresAt>Date.now()?'本机推荐中':'已结束'} · 截止 {new Date(b.expiresAt).toLocaleString('zh-CN')}</small></p>)}</div>}</section>}
 {tab==='rules'&&<section className="garden-rules"><h4>只奖励完成的接力</h4><p>普通交易：20 成长值 + 1 张演示券。<br/>免费接力：40 成长值 + 2 张演示券。</p><p>同一 Item ID 只奖励一次；重复点击、修改版本、上传历史凭证都不会重复发奖。无需签到、刷浏览或邀请好友。</p><p>成长记录、照片故事和奖励仅保存在当前浏览器。换设备不会同步；清除浏览器数据会清除进度。</p><p>当前双方确认属于演示。正式跨用户奖励与推流需要独立登录、真实双方确认及服务端防刷规则；当前不提供碳减排量或公益承诺。</p></section>}
 {selected&&<section ref={editorRef} className="garden-story-editor" aria-label="编辑接力故事"><h4>{selected.name}</h4><p>物主陈述 · 故事不会变成可核验的交易凭证。</p><textarea aria-label="这件物品的接力故事" maxLength={180} value={story} onChange={e=>setStory(e.target.value)} placeholder="例如：陪我度过毕设的台灯，今天有了下一位主人。"/><div><button className="outline-button" onClick={()=>setSelected(null)}>取消</button><button className="btn purple" onClick={saveStory}>保存故事</button></div></section>}
 </div>
}
